<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0</TargetFrameworks>
    <PackageId>TL.BaseContracts</PackageId>
    <Description>Fundação padronizada e unificada de contratos em BCL pura (Commands, Queries, Events, Results, Errors e Paginações) para aplicações .NET modernas e legadas.</Description>
    <PackageTags>contracts;result-pattern;cqrs;clean-architecture;ddd;error-handling;tl</PackageTags>
  </PropertyGroup>

</Project>