<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net8.0;net9.0</TargetFrameworks>
    <PackageId>TL.InvokePrivate</PackageId>
    <Description>Utilitário para invocação dinâmica de membros privados via Reflection com desembrulho automático de exceções de negócio para compatibilidade em testes legados em .NET 6, .NET 8 e .NET 9.</Description>
    <PackageTags>reflection;invoke;private-methods;testing;legacy;csharp;dotnet;net6;net8;net9;tl</PackageTags>
  </PropertyGroup>

</Project>
