<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>

    <!-- NuGet Package Metadata -->
    <IsPackable>true</IsPackable>
    <PackageId>CommonHelpers.HealthCheck</PackageId>
    <Version>0.0.1-beta.1</Version>
    <Authors>Equipe de Engenharia e Arquitetura</Authors>
    <Company>Corporativo</Company>
    <Product>CommonHelpers Suite</Product>
    <Description>Configuração simplificada e padronizada de Health Checks (Liveness, Readiness, UI Client) para ASP.NET Core e Worker Services em .NET 8 e .NET 9.</Description>
    <PackageTags>healthchecks;liveness;readiness;aspnetcore;workerservice;monitoring;kubernetes;diagnostics</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
