<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <PackageId>TL.MiddlewareLibrary</PackageId>
    <Description>Biblioteca modular de middlewares para ASP.NET Core (.NET 8 e .NET 9) com foco em diagnósticos de latência, controle de taxa por IP, cache em memória e padronização de respostas de erro RFC 7807 (ProblemDetails) integrada a TL.BaseContracts.</Description>
    <PackageTags>aspnetcore;middleware;problem-details;rfc7807;rate-limiting;caching;timing;authentication;http;zero-allocation;tl</PackageTags>
  </PropertyGroup>

  <!-- Framework Nativo ASP.NET Core -->
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TL.BaseContracts\TL.BaseContracts.csproj" />
  </ItemGroup>

</Project>
